"""
Django settings for Montada project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q$zsfembchk%)jfss=7a)e%_)yfv377x_=2%3wg3!a=&s2%gn6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Hostnames only (no https:// or trailing slash). '*' allows all.
ALLOWED_HOSTS = [
    "*",
    "localhost",
    "127.0.0.1",
    "app.themontada.com",
    "uat.themontada.com",
    "www.uat.themontada.com",
    "adminuat.themontada.com",
    "admin.themontada.com",
    "api.themontada.com",
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'daphne',  # ASGI server; must be before django.contrib for runserver WebSocket support
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    # custom apps
    'Mainapp',
    'Subscriptions',
    'Signals',
    'Followers',
    'Dashboard',
    'MontadaAdmin',
    'News',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS: allow localhost on any port + your web origins (no trailing slashes)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5000",
    "http://localhost:8080",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5000",
    "http://127.0.0.1:8080",
    "https://api.themontada.com",
    "https://app.themontada.com",
    "https://uat.themontada.com",
    "https://adminuat.themontada.com",
    "https://admin.themontada.com",
]
# Allow any localhost / 127.0.0.1 port (e.g. 5173, 4200, 3001)
CORS_ALLOWED_ORIGINS_REGEX = r"^https?://(localhost|127\.0\.0\.1)(:\d+)?$"
# Required if frontend sends cookies or Authorization header
CORS_ALLOW_CREDENTIALS = True
# Allow common headers and methods

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "origin",
    "x-requested-with",
]

ROOT_URLCONF = 'Montada.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Montada.wsgi.application'
ASGI_APPLICATION = 'Montada.asgi.application'

# Channels / Redis for live chat WebSockets
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
        'default': {
        'ENGINE': 'mssql',
        'NAME': 'MotadaApp',
        'USER': 'MontadaUser',
        'PASSWORD': 'A7f#Q9mL@2xR!K8Z',
        'HOST' : '185.4.178.134',
        'PORT': '1433',
        'CONN_MAX_AGE':120,

        # 'ENGINE': 'mssql',
        # 'NAME': 'MontadaApp',
        # 'USER': 'MontadaUser',
        # 'PASSWORD': 'A7f#Q9mL@2xR!K8Z',
        # 'HOST': '3.76.105.23',
        # 'PORT': '1433',

        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
        },
       
    },

    'mt5clients': {
        'ENGINE': 'mssql',
        'NAME': 'METATRADER5',
        'USER': 'tinstcrm',
        'PASSWORD': 'Trust_2021',
        'HOST': '213.175.205.19',
        'PORT': '1433',

        #  'OPTIONS': {
        #     'driver': 'ODBC Driver 18 for SQL Server',
        #     'extra_params': 'Encrypt=no;TrustServerCertificate=yes;',
        # },
       
        
    },
}


CSRF_TRUSTED_ORIGINS = [
    "https://api.themontada.com",
    "https://uat.themontada.com",
    "https://www.uat.themontada.com",
    "http://localhost:8080",
    "https://adminuat.themontada.com",
    "https://admin.themontada.com",
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'Mainapp.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),   # 1 year
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),  # 1 year
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Base URL for absolute media URLs in API responses (e.g. article featured_image)
PUBLIC_MEDIA_BASE_URL = 'https://api.themontada.com'

# Marketaux API for market/finance news (https://www.marketaux.com/documentation). Sign up for a free token.
MARKETAUX_API_TOKEN = "vIWcnrrYFI0FBaNnAgD0DAeiQ2prDE7QakmniN9h"

# Email configuration
# Configure these settings with your email provider credentials
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Change to your SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'montadaapp129@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'thtchyjfmdndibtd'  # Your email password or app-specific password
# DEFAULT_FROM_EMAIL = ''  # Default sender email address

# For Gmail, you may need to use an App Password instead of your regular password
# For other providers, adjust EMAIL_HOST, EMAIL_PORT, EMAIL_USE_TLS/EMAIL_USE_SSL accordingly

# ForexNewsAPI (events / trending-headlines still use this provider unless overridden)
FOREXNEWS_API_TOKEN    = "ix9zm1aqfxqzclsusns6cqsaufji9k3lpdcy0ybs"
FOREXNEWS_EVENTS_URL   = "https://forexnewsapi.com/api/v1/events"
FOREXNEWS_TRENDING_URL = "https://forexnewsapi.com/api/v1/trending-headlines"
FOREXNEWS_CATEGORY_URL = "https://forexnewsapi.com/api/v1/category"

# EODHD Financial News API — used for category news (see News.ForexCategoryNewsView)
# https://eodhd.com/financial-apis/stock-market-financial-news-api/
EODHD_API_TOKEN = os.environ.get("EODHD_API_TOKEN", "69ba6abb136cc3.30994192") or FOREXNEWS_API_TOKEN
EODHD_NEWS_URL = os.environ.get("EODHD_NEWS_URL", "https://eodhd.com/api/news")

# Analyst content-plan paywall:
# When True, traders can view analyst signals and analyst articles without holding
# an active UserAnalystPlanSubscription. Signal follow rules still apply separately.
ANALYST_SUBSCRIPTION_FREE_ACCESS = True

# MT5 Manager API (for run_price_alerts --use-mt5-manager). Optional; can use env vars instead.
MT5_MANAGER_SERVER   = os.environ.get("MT5_MANAGER_SERVER", "207.97.203.117:443")   # e.g. "192.168.1.100:443"
MT5_MANAGER_LOGIN    = os.environ.get("MT5_MANAGER_LOGIN", "5022")    # e.g. 1002
MT5_MANAGER_PASSWORD = os.environ.get("MT5_MANAGER_PASSWORD", "YlCcG-3u") # manager password



LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
