# Generated by Django 5.2.9 on 2026-01-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Subscription status of the user'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('trader', 'Trader'), ('analyst', 'Analyst')], default='trader', help_text='Whether the user is a trader or analyst', max_length=10),
        ),
    ]
