from django.urls import path
from .views import (
    AdminLoginView,
    AdminCreateAnalystView,
    AdminCreateTraderView,
    AdminChangeUserPasswordView,
    AdminSuspendUserView,
    AdminUserProfileView,
    AdminDashboardStatsView,
    AdminSignalsStatsView,
    AdminSignalsListView,
    AdminCreateSignalView,
    AdminSignalStatusesView,
    AdminSignalAssetsView,
    AdminSignalInstrumentsView,
    AdminSignalTimeframesView,
    AdminNewsCategoryListView,
    AdminNewsCategoryCreateView,
    AdminNewsArticleStatsView,
    AdminNewsArticleListView,
    AdminNewsArticleCreateView,
    AdminNewsArticleDetailView,
    AdminNewsArticleUnpublishView,
    AdminPollStatsView,
    AdminPollsListView,
    AdminPollCreateView,
    AdminPollQuestionDetailView,
    AdminPollUnpublishView,
    AdminPollOptionAddView,
    AdminPollOptionDeleteView,
    AdminPollQuestionCloseView,
    WinRateByPeriodView,
    AdminDashboardGraphsView,
    TopAnalystLeaderboardView,
    AdminAnalystListView,
    AdminTraderListView,
    AdminGetMarketDataFromMT5,
    AdminMarketNewsList,
    AdminSubscriptionStatsView,
    AdminMRRView,
    AdminPaymentHistoryView,
    AdminFCMBroadcastView,
    AdminUserPickerView,
)

app_name = "MontadaAdmin"

urlpatterns = [
    path("login/", AdminLoginView.as_view(), name="admin_login"),
    path("dashboard/stats/", AdminDashboardStatsView.as_view(), name="admin_dashboard_stats"),
    path("dashboard/winrate/", WinRateByPeriodView.as_view(), name="admin_winrate_by_period"),
    path("dashboard/graphs/", AdminDashboardGraphsView.as_view(), name="admin_dashboard_graphs"),
    path("dashboard/leaderboard/", TopAnalystLeaderboardView.as_view(), name="admin_top_analyst_leaderboard"),


    path("users/analysts/", AdminAnalystListView.as_view(), name="admin_analyst_list"),
    path("users/analysts/create/", AdminCreateAnalystView.as_view(), name="admin_create_analyst"),
    path("users/traders/", AdminTraderListView.as_view(), name="admin_trader_list"),
    path("users/traders/create/", AdminCreateTraderView.as_view(), name="admin_create_trader"),
    path("users/change-password/", AdminChangeUserPasswordView.as_view(), name="admin_change_user_password"),
    path("users/suspend/", AdminSuspendUserView.as_view(), name="admin_suspend_user"),
    path("users/<uuid:user_id>/", AdminUserProfileView.as_view(), name="admin_user_profile"),

    path("signals/signals-stats/", AdminSignalsStatsView.as_view(), name="admin_signals_stats"),
    path("signals/", AdminSignalsListView.as_view(), name="admin_signals_list"),
    path("signals/create/", AdminCreateSignalView.as_view(), name="admin_signal_create"),
    path("signals/filters/statuses/", AdminSignalStatusesView.as_view(), name="admin_signal_statuses"),
    path("signals/filters/assets/", AdminSignalAssetsView.as_view(), name="admin_signal_assets"),
    path("signals/filters/instruments/", AdminSignalInstrumentsView.as_view(), name="admin_signal_instruments"),
    path("signals/filters/timeframes/", AdminSignalTimeframesView.as_view(), name="admin_signal_timeframes"),

    path("news/categories/", AdminNewsCategoryListView.as_view(), name="admin_news_category_list"),
    path("news/categories/create/", AdminNewsCategoryCreateView.as_view(), name="admin_news_category_create"),
    path("news/articles/stats/", AdminNewsArticleStatsView.as_view(), name="admin_news_article_stats"),
    path("news/articles/", AdminNewsArticleListView.as_view(), name="admin_news_article_list"),
    path("news/articles/create/", AdminNewsArticleCreateView.as_view(), name="admin_news_article_create"),
    path("news/articles/<uuid:pk>/", AdminNewsArticleDetailView.as_view(), name="admin_news_article_detail"),
    path("news/articles/<uuid:pk>/unpublish/", AdminNewsArticleUnpublishView.as_view(), name="admin_news_article_unpublish"),

    path("polls/stats/", AdminPollStatsView.as_view(), name="admin_poll_stats"),
    path("polls/", AdminPollsListView.as_view(), name="admin_polls_list"),
    path("polls/create/", AdminPollCreateView.as_view(), name="admin_poll_create"),
    path("polls/<uuid:pk>/", AdminPollQuestionDetailView.as_view(), name="admin_poll_question_detail"),
    path("polls/<uuid:pk>/unpublish/", AdminPollUnpublishView.as_view(), name="admin_poll_unpublish"),
    path("polls/<uuid:pk>/close/", AdminPollQuestionCloseView.as_view(), name="admin_poll_question_close"),
    path("polls/<uuid:question_pk>/options/", AdminPollOptionAddView.as_view(), name="admin_poll_option_add"),
    path("polls/<uuid:question_pk>/options/<uuid:option_pk>/", AdminPollOptionDeleteView.as_view(), name="admin_poll_option_delete"),

    path("marketdata/live/", AdminGetMarketDataFromMT5.as_view(), name="admin_marketdata_live"),
    path("news/market-news/", AdminMarketNewsList.as_view(), name="admin_market_news"),

    path("subscriptions/stats/", AdminSubscriptionStatsView.as_view(), name="admin_subscription_stats"),
    path("subscriptions/mrr/", AdminMRRView.as_view(), name="admin_subscription_mrr"),
    path("subscriptions/payments/", AdminPaymentHistoryView.as_view(), name="admin_payment_history"),

    path("notifications/broadcast/", AdminFCMBroadcastView.as_view(), name="admin_fcm_broadcast"),
    path("notifications/user-picker/", AdminUserPickerView.as_view(), name="admin_user_picker"),
]

